name: Useless Tools
main: riseofdeath.uselesstools
author: RiseOfDeath aka ROD
version: 0.3.2
commands:
  generate: 
    description: initial world generation
    usage: generate <world> <x1> <y1> <x2> <y2>
  statistic: 
    description: Counting blocks
    usage: statistic <world> <x1> <y1> <x2> <y2>